<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<IgnoreModFilePatterns>\.dll$, \.pdb$</IgnoreModFilePatterns>
	</PropertyGroup>

	<ItemGroup>
		<None Update="content.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="assets/Match3/*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="assets\Match3\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.3.0" />
	</ItemGroup>
</Project>