<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<EnableHarmony>true</EnableHarmony>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="Steamworks.NET">
			<HintPath>$(GamePath)\Steamworks.NET.dll</HintPath>
		</Reference>
		<Reference Include="ContentPatcher">
			<HintPath>$(GamePath)\Mods\ContentPatcher\ContentPatcher.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<None Include="..\.editorconfig" Link=".editorconfig" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.3.2" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="StardewValley" />
		<Using Include="Microsoft.Xna.Framework" />
		<Using Include="Microsoft.Xna.Framework.Graphics" />
	</ItemGroup>

	<ItemGroup>
		<ContentPacks Include="../[CP] Hikawa" Version="$(Version)">
			<IgnoreModFilePaths>bin/.*, obj/.*</IgnoreModFilePaths>
			<IgnoreModFilePatterns>\.dll$, \.pdb$, \.csproj$</IgnoreModFilePatterns>
		</ContentPacks>
	</ItemGroup>

	<ItemGroup>
		<Content Include="../[CP] Hikawa/**" Link="_[CP] Hikawa\%(RecursiveDir)\%(FileName)%(Extension)" CopyToOutputDirectory="Never" />
	</ItemGroup>

</Project>